### ISSUE TITLE
http://export.highcharts.com/ - is Map constructor working?

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-export-server#1]
I am unable to create any map chart using Map constructor.
I tried using JSON from demos linked below, but all Previews ended up with `Error: Internal Server Error` and Download gives `Oops.., Timeout converting SVG, is your file this big, or maybe you have a syntax error in the javascript callback?`

Simple map: http://jsfiddle.net/vfLpt5v4/
Empty map: http://jsfiddle.net/277ph64g/

**Comment by gvaartjes** [comment]
Maps isn't supported for server-side rendering

**Comment by ooriol** [comment]
Is it supposed to be fixed server-side rendering at some point?
Thanks

**Comment by gvaartjes** [comment]
I guess so, but we have to test the performance of Phantomjs and perhaps the limit of data you can upload. In case of maps data, these can be quite large.

**Comment by Jacobss** [comment]
I just ran into this issue today as well.  What is the workaround?  If I set up my own export server would there be a way to get it working?  Thanks!

**Comment by TorsteinHonsi** [comment]
> In case of maps data, these can be quite large.

In most cases it shouldn't be a problem. But we need to host the [mapdata](http://code.highcharts.com/mapdata/) locally on the export server instead of loading it from code.highcharts.com.

**Comment by ooriol** [comment]
or it can be part as part of the json that we send to the export server like this:
http://jsfiddle.net/vfLpt5v4/
so no need to host mapData in the export server, right?
Thanks!

**Comment by TorsteinHonsi** [comment]
> so no need to host mapData in the export server, right?

You're right, I would expect this config to work already:
```js
{
    "series": [{
        "mapData": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "id": "US.MA",
                "properties": {
                    "hc-key": "us-ma"
                },
                "geometry": {
                    "type": "MultiPolygon",
                    "coordinates": [
                        [
                            [
                                [9314, 7915],
                                [9312, 7927],
                                [9304, 7921],
                                [9278, 7938],
                                [9254, 7990],
                                [9177, 7968],
                                [8997, 7925]
                            ]
                        ]
                    ]
                }
            }]
        },
        "data": [{
            "hc-key": "us-ma",
            "value": 42
        }],
        "joinBy": ["hc-key"]
    }]
}
```

**Comment by Jacobss** [comment]
@TorsteinHonsi I just tried that config on export.highcharts.com and still got the usual "Error: Internal Server Error".

**Comment by gvaartjes** [comment]
Yes, that's right I didn't fix it yet, sorry. But it's on my radar.

**Comment by gvaartjes** [comment]
Tested the export server with the above config (posted by @TorsteinHonsi ) and it works.

**Comment by Jacob-Lynch** [comment]
@gvaartjes This appears to be broken again.  The map constructor does not work on the export server with the above config.

**Comment by gvaartjes** [comment]
@Jacob-Lynch 
I'm sorry. We're on to it. This should be fixed in 30 minutes from now

**Comment by Jacob-Lynch** [comment]
@gvaartjes Yes it is working again, thank you!
