### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by achahal** [highcharts/highcharts-export-server#11]
We have installed java server locally, and is running on jetty. The problem is on trying to generate the chart we get following error.
![image](https://cloud.githubusercontent.com/assets/18575081/14783814/6afd1d40-0af2-11e6-9c32-d6531cedd3ea.png)

To test we are using embedded web app at http://localhost:9001/export/

We also tried posting following simple JSON via POSTMAN, 
`{
    "infile": "{xAxis: {categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']},series: [{data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]}]};",
    "callback": "function(chart) {chart.renderer.arc(200, 150, 100, 50, -Math.PI, 0).attr({fill : '#FCFFC5',stroke : 'black','stroke-width' : 1}).add();}",
    "constr": "Chart"
}`

This works against  http://export.highcharts.com/json/abc.png but not with our local java highchart export server.

Everything else is default in 
![image](https://cloud.githubusercontent.com/assets/18575081/14783924/1f723f62-0af3-11e6-8041-27c5f5eee130.png)

Simple steps I followed to install server:

1. git clone https://github.com/highcharts/highcharts-export-server.git
2. mvn install
3. cd java/highcharts-export/highcharts-export-web
4. install phantonjs 2 
5. mvn jetty:run

**Comment by larsac07** [comment]
Hi, @achahal.

From your description, it seems you might have skipped a step in the [guide](http://www.highcharts.com/docs/export-module/setting-up-the-server). You have to run `mvn install` from java/highcharts-export/, which installs both the highcharts-export-convert (dependency) and the highcharts-export-web projects.

**Comment by larsac07** [comment]
Assuming issue was user error and resolved. Closing for now. Feel free to open again if the issue was not resolved.
