### ISSUE TITLE
New way of loading resources - is it documented?

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-export-server#14]
Looks like new way of loading resources is not documented in Docs: http://www.highcharts.com/docs/export-module/render-charts-serverside (*The dependency and location of these files is configured in the highcharts-convert.js script.*) or anywhere else.

**Comment by gvaartjes** [comment]
Oops, I thought I updated the docs, but I missed this one. Thx!

**Comment by gvaartjes** [comment]
It is now!
