### ISSUE TITLE
Enhancement: ajax calls in chart's callback

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-export-server#15]
Would it be possible to allow ajax calls in chart's callback when using phantomjs from console?
Currently the server waits for images to be loaded, so I guess logic could be similar.

I was able to force waiting by loading an image that is delayed using `http://deelay.me/500/http://examplesite.com/image.gif` and hopefully ajax with `async: false` is finishing before image is loaded. This way waiting time is maximized to timeout time, so it's not great.

**Comment by larsac07** [comment]
@cvasseng

**Comment by larsac07** [comment]
Agreed, that would be a good enhancement. We would need to require a standardized way of notifying phantom that the ajax call is complete, so that the image may be captured at the right time, or else the server will start hanging.

**Comment by larsac07** [comment]
Closing this, as further enhancements will not be implemented on this repo (new export server at https://github.com/highcharts/node-export-server)
