### ISSUE TITLE
phantomjs -callback problem

### ISSUE THREAD

**Issue by yangguangbuxiumaomao** [highcharts/highcharts-export-server#17]
hi,i used `phantomjs highcharts-convert.js -infile options.json -outfile chart.png -scale 2.5 -width 600 -callback callback.js` to export .png charts;
but i got a problem, 
following is my callback.js
```
function(){
    Highcharts.setOptions({
              title:{
                  text:"title"
                 },
              plotOptions:{
                 dataLabels:{
                    .......
                }
             }
   });
} 
```

but this callback function did not work,could u tell me why, if you don't mind.

**Comment by larsac07** [comment]
Hi, @yangguangbuxiumaomao. Your callback function is not altering the chart created, because you are not setting the options on the created chart. You have to pass the chart to the callback function, and set the options on it via the `update()` function, like this:
```
function(chart){
    chart.update({ // takes two arguments: options and redraw
        title:{
            text:"title"
        },
        plotOptions:{
            dataLabels:{
                .......
            }
        }
    }, true); // whether or not to redraw the chart
} 
```
