### ISSUE TITLE
Error in resources parsing

### ISSUE THREAD

**Issue by maxupp** [highcharts/highcharts-export-server#18]
When parsing resources (line 682 in version 2.0.1) the variable resources is undefined:

fileList = resources.split('\,');

At this point it should be:

fileList = params.resources.split('\,');

When attempting to use this code without the fix it will hang the program without an error message.

**Comment by larsac07** [comment]
You're right, @maxupp. Thank you for noticing.

Created a fix from your description and tested with running the `highcharts-convert.js` script from phantomjs with the `-resources` param as a list of comma-separated filenames. It hung up with no error message without the fix, and worked flawlessly with the fix.
