### ISSUE TITLE
Java export server fails after doing automatic re-deployment

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts-export-server#19]
System: tomcat 8.0.32-1ubuntu1.1 running on Ubuntu 16.04 x64

Whenever I re-deploy the Java export server, it will fail to run correctly until I either restart tomcat8 or kill any existing phantomjs processes.

When I try to click the "preview" button on the export server default page straight after doing the re-deployment, an error appears in catalina.out.

The error below is from trying to run the "preview" button four times in succession.

```
[ERROR] [http-nio-8080-exec-25 05:19:49] (ExportController.java:writeFileToStream:356) Tried to read file from filesystem: File '/tmp/tomcat8-tomcat8-tmp/export4935023327417038147/output/UOBhqYub.png' does not exist
[ERROR] [http-nio-8080-exec-18 05:19:51] (ExportController.java:writeFileToStream:356) Tried to read file from filesystem: File '/tmp/tomcat8-tomcat8-tmp/export4935023327417038147/output/QWiDbLf9.png' does not exist
[ERROR] [http-nio-8080-exec-24 05:19:52] (ExportController.java:writeFileToStream:356) Tried to read file from filesystem: File '/tmp/tomcat8-tomcat8-tmp/export4935023327417038147/output/nQS4IOvc.png' does not exist
[ERROR] [http-nio-8080-exec-28 05:21:08] (ExportController.java:writeFileToStream:356) Tried to read file from filesystem: File '/tmp/tomcat8-tomcat8-tmp/export4935023327417038147/output/e1qVP7aZ.png' does not exist
```

**Comment by gandhrekunal** [comment]
I am facing the same issue @tomascassidy @TorsteinHonsi @gvaartjes @havardge @cvasseng 

Please help me out :+1:

**Comment by gvaartjes** [comment]
@larsac07 @havardge Please inspect the addShutdownHook in Server.java

**Comment by gandhrekunal** [comment]
Thanks, @gvaarties, I am trying  to setup server on Windows as well on Linux using tomcat8 and mvn jetty:run, I'm getting response as " ReferenceError: Can't find variable: highcharts". I have added required js files in resource/phontomjs directory and mentioned these files in resources.json. 

Kindly request you to help me out 😞

**Comment by larsac07** [comment]
@tomascassidy: Getting the same issue when running locally on OSX with jetty server, and trying to preview or download (damaged png images) with config object. Looking into it

@gandhrekunal: The issue you are describing seems to be something much different than the original post. If you could kindly submit a separate issue or a post on the [forum](http://forum.highcharts.com/highcharts-usage/) and describe your setup in more detail, we may help you.

**Comment by gandhrekunal** [comment]
I have post new issue,

Please check the below URL

https://github.com/highcharts/highcharts-export-server/issues/20

**Comment by larsac07** [comment]
Commit ad57103 fixes the issue.
