### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by d0x** [highcharts/highcharts-export-server#2]
All charts are failing with an `SocketTimeoutexception` on the current master.

How to reproduce: 

1. Checkout the new repository
2. cd into `highcharts-export-server/java`
2. Add the correct phantomjs 2.0.0 path: `echo -e "\nexec=/usr/bin/phantomjs" >> highcharts-export/highcharts-export-web/src/main/webapp/WEB-INF/spring/app-convert.properties`
2. run mvn install on `highcharts-export`
3. run mvn jetty:run on `highcharts-export/highcharts-export-web`
4. open `http://localhost:8080/export/` and click download.

Then I get this error:

```
[ERROR] [qtp560549459-16 03:08:06] (SVGConverter.java:requestServer:133) java.net.SocketTimeoutException: Read timed out
Dec 11, 2015 3:08:06 PM com.highcharts.export.interceptor.RequestInterceptor afterCompletion
INFO: Time=Fri Dec 11 15:08:06 CET 2015 :: Time taken(ms) 6,019
 :: RequestMethod POST :: Status 500 :: Referer=http://localhost:8080/export/
 :: Request parameters  constr=Chart, 
        options={
        xAxis: {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        series: [{
                data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 
                        135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        }]
};
, 
        width=, 
        scale=, 
        callback=, 
        type=image/png, 
        content=options, 
Dec 11, 2015 3:08:06 PM com.highcharts.export.interceptor.RequestInterceptor afterCompletion
```

System:

* Ubuntu
* PhantomJS 2.0.0
* Java 1.8

P.S.: Maybe you add also the last version as an tag to this repository. So i don't need to checkout the nighly build every time i redeploy my system.

**Comment by d0x** [comment]
I have the same problem with V 4.1.9 which i downloaded from the old repository

**Comment by d0x** [comment]
I figured out that the exception is thrown here: https://github.com/highcharts/highcharts-export-server/blob/9bbf7b56a5a48ce58844d8f046a690ca55c4d0e3/java/highcharts-export/highcharts-export-convert/src/main/java/com/highcharts/export/server/Server.java#L122 

The strange thing is that phantomjs servers are running:

![image](https://cloud.githubusercontent.com/assets/2202723/11746658/61f7e16e-a01f-11e5-9b4f-58bfda3da2c0.png)

**Comment by d0x** [comment]
Okay, the phantomjs servers where started by some older tries.
The problem was that i haven't shutdown the exportserver gracefully I guess.

I did `pkill -9 phantomjs` followed `mvn jetty:run` and it works fine now.

Thank you.

**Comment by VK0X** [comment]
I'm facing the same issue. I also killed all the instances of phantomjs but to no use. 
System:
Windows Server 2008 r2
PhantomJS 2.0.0
Java 1.8.0_71
Maven 3.3.9

**Comment by bherrnboeck** [comment]
Same Problem for me. No updated yet?

**Comment by dzuluaga** [comment]
Same here.
