### ISSUE TITLE
Java export server : (SVGConverter.java:convert:108) responce : ReferenceError: Can't find variable: Highcharts

### ISSUE THREAD

**Issue by gandhrekunal** [highcharts/highcharts-export-server#20]
System : windows 10 and AWS EC2

I have follow below steps: 

1. install jdk
2. install tomcat8
3. install maven
4. PhantomJS
5. Updated app-convert.properties according to system (windows/linux)
6. Added new required highchart java-script files in diectory _**/phantomjs**_
7. Updated required java-scripts files names in **_resources.json_**
5. Export war/ install export server from repository
6. Deploy war in tomcat/ start server using mvn jetty:run

On preview server logs error 
`[ERROR] [http-nio-8080-exec-25 05:19:49] (ExportController.java:writeFileToStream:356) Tried to read file from filesystem: File '/tmp/tomcat8-tomcat8-tmp/export4935023327417038147/output/UOBhqYub.png' does not exist`

So I debug Server.java, server is responding as 
`"ReferenceError: Can't find variable: highcharts". `

I have added required js files in resource/phontomjs directory and mentioned these files in resources.json.

Please correct me if I am missing anything.
Thanks, @TorsteinHonsi @gvaartjes @havardge @cvasseng @jon-a-nygaard

**Comment by gandhrekunal** [comment]
My bad, my stupid mistake, I was using old version of highchart java-scripts files.

**Comment by gandhrekunal** [comment]
I have debug the code

(SVGConverter.java:convert:108) responce json: ReferenceError: Can't find variable: Highcharts

**Comment by larsac07** [comment]
Thank you, @gandhrekunal. This really helps. Your supplied information indicates that the problem may indeed be related to #19, as you suggested. I'm looking into this now

**Comment by larsac07** [comment]
The problem does not seem to be related to #19 where the issue was that on a redeploy, the folders for output and input were not synched. The issue here is phantomJS not with finding the Highcharts object. @gandhrekunal, could you please provide a list of the contents in your `highcharts-export-server-repo/java/highcharts-export/highcharts-export-convert/src/main/resources/phantomjs/` folder, and the contents of your `app-convert.properties`?

**Comment by gandhrekunal** [comment]
Thanks @larsac07 
The issue is resolved now, I did some mistake while adding JavaScript files in `resources`
apologies for the inconvenience.

**Comment by larsac07** [comment]
Ah, no worries! It happens ;) I am glad you solved your problem.
