### ISSUE TITLE
The highcharts-convert.js can't show Chinese word

### ISSUE THREAD

**Issue by DennisXie** [highcharts/highcharts-export-server#21]
I've write some Chinese word in xAxis title. After I convert the svg to jpeg/png using highcharts-convert.js,  there is no Chinese word in the jpeg or png files.

**Comment by DennisXie** [comment]
I've tried to apt-get install xfonts-wqy and set the phantomjs --output-encoding=gbk, but it doesn't work.

**Comment by larsac07** [comment]
Hi, @DennisXie. Could you please provide the following information:
- your chart configuration
- server type and version
- java version
- phantomjs version
- fonts installed on your server

**Comment by DennisXie** [comment]
Hi, @larsac07 . After I installed the ttf-dejavu and ttf-wqy-microhei, it works~

**Comment by DennisXie** [comment]
Debian GNU/Linux 8
Java 1.7.0
Phantomjs 2.1.1
