### ISSUE TITLE
why no wait for loading of chart before page.render in highcharts-convert.js

### ISSUE THREAD

**Issue by aagRayad** [highcharts/highcharts-export-server#22]
Hi guys, i am a phantomjs enthusiast. We know that since it takes some time to load the charts so we have to add a waiting time before rendering any page. But while i was going through highcharts-convert.js I could not see any waiting time before page.render. The code only waits if the svg has some image tags, but many times the svg does not have any image tags so how does the script take care of the fact that the chart was loaded before page.render. Does the highcharts library take care of this fact?

**Comment by KacperMadej** [comment]
Hi,

Thank you for notifying us about the issue. We are working on possible improvements in PhantomJS chart rendering and will take this issue into consideration.

**Comment by larsac07** [comment]
The highcharts-convert script waits for chart.load() to be called before rendering the page, as of commit c7c3f3a2
