### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by Argschnarbler** [highcharts/highcharts-export-server#28]
Followed the installation instructions to the best of my ability.
When I execute:
phantomjs highcharts-convert.js -host 127.0.0.1 -port 3003

It just hangs and never produces any output.
Any ideas?

**Comment by larsac07** [comment]
@Argschnarbler `phantomjs highcharts-convert.js -host 127.0.0.1 -port 3003` starts a web server that listens to `POST` requests. If this was your intention, what does your `POST` request look like?

If it was not your intention to start a web server, but only make phantomjs export a chart, try running `phantomjs highcharts-convert.js -infile options.js -outfile chart.png -scale 2.5 -width 300` (check the available command line arguments on http://www.highcharts.com/docs/export-module/render-charts-serverside.

If you simply want to set up an export server with Java and PhantomJS, you need to follow section 2 to 2.4 and select a server type. I think the easiest would be to use Jetty, explained in section 2.6:

> We added the Jetty Server dependency in pom.xml file for testing convenience. For running the export-server locally, during development, navigate in a DOS/Shell to the highcharts-export/highcharts-export-web folder, and run this command: mvn jetty:run. This starts the Jetty application server and the application is now accessible at http://localhost:8080/export.

**Comment by larsac07** [comment]
Assuming the problem was fixed after no response for a time. @Argschnarbler feel free to reopen this issue if that is not the case.
