### ISSUE TITLE
xAxis.labels.useHTML does not have the desired effect

### ISSUE THREAD

**Issue by jb3-2** [highcharts/highcharts-export-server#30]
Hi, 

I'd like to create a space between two columns by adding a html no-breaking-space as x axis label. That [works perfectly](https://statabs.github.io/indikatoren/chart.html?kuerzel=I.50.2.0001) when rendering a chart in the browser. If, however, an svg is rendered by the export server, the html code is[ displayed in the chart](https://statabs.github.io/indikatoren/images/portal/I.50.2.0001.svg). 

The problem can be reproduced by convertig [this highcharts configuration](https://statabs.github.io/indikatoren/charts/configs/portal/I.50.2.0001.json) to an svg using the [demo export](http://export.highcharts.com/demo) server. 

Any idea how I can get a better svg from the export server? Thanks for your help!
J.

**Comment by TorsteinHonsi** [comment]
Hi,

Adding non-breaking spaces is a bit of a hack to what you want to achieve - in this situation I would rather add `xAxis.categories` with empty slots: http://jsfiddle.net/highcharts/oegqa97h/. Now you can also remove the names from each point definition and add only the Y value.

**Comment by jb3-2** [comment]
Hi Torstein,

Thanks for your quick reply, that works perfectly. Keep up the great work! 

J.
