### ISSUE TITLE
Chart is not fully rendered in styled mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts-export-server#31]
Rendering a chart using PhantomJS method, described here: http://www.highcharts.com/docs/export-module/render-charts-serverside with data from this demo: http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/axis/ results in an incomplete chart, presented below:

![chart](https://cloud.githubusercontent.com/assets/19933566/20054513/7d2b790a-a4dd-11e6-8918-3d7cca443eee.png)

Content of resources.json file looks as follows:

`{
    "files": "highcharts-styled.js,css/style.css"
}`

where highcharts-styled.js is Highcharts in a styled mode and style.css is a stylesheet desired to add. When using Highcharts in a classic mode, everything works as it should (style is applied correctly). It seems that importing css (@import 'https://code.highcharts.com/css/highcharts.css') causing this because rendering chart with this part of code commented, looks like this:

![chart](https://cloud.githubusercontent.com/assets/19933566/20055026/9fe60080-a4df-11e6-99dc-9f0da2b7f532.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/axis/

**Comment by TorsteinHonsi** [comment]
Does it work if you don't rely on the @import and instead define the CSS file directly?

`{ "files": "highcharts-styled.js,css/highcharts.css,css/style.css" }`

**Comment by PaulDalek** [comment]
When CSS file is defined directly, generating chart using PhantomJS results in trimmed image.

![chart](https://cloud.githubusercontent.com/assets/19933566/20103039/a46dc2d4-a5c8-11e6-8f0f-6ee284ca814c.png)

**Comment by larsac07** [comment]
Just to compare, this is what I have found:
- When it is both imported and added to resources it gets trimmed like the post just above this one
- When it is only added to resources it gets trimmed on the right side, probably due to the width being set with #container.max-width instead of #container.width
- When it is only being imported, it looks like the black image in the original post
- Before commit ff0b15fd, it just always results in a black image

**Comment by larsac07** [comment]
After testing with vanilla phantom examples, it seems like phantom does not support the `@import` function in css. `highchats-convert.js` will therefore have to look for imports in css files, download and paste the contents inside `<style>` elements.

**Comment by larsac07** [comment]
This issue has now been partially fixed (missing support for SVG) by moving CSS `@import`-statements to HTML `<link>`-tags.

A fix for SVG is described in PR #32 and coming.

**Comment by lalitkt4** [comment]
Hii,
    I have issue with chart label.
My OS is centos 6.8 and phantom js version 1.9.8
![img](https://user-images.githubusercontent.com/29541993/30915772-6e89e95e-a3b5-11e7-9cfc-d59cbcfb776d.png)
