### ISSUE TITLE
Publish highcharts-export-server on NPM

### ISSUE THREAD

**Issue by RemiAWE** [highcharts/highcharts-export-server#4]
It will be useful if you can publish this repository on NPM please

**Comment by TorsteinHonsi** [comment]
@gvaartjes But this repo contains mostly Java code?

**Comment by gvaartjes** [comment]
@TorsteinHonsi I guess @RemiAWE means the phantomjs based export-server.

**Comment by nfantone** [comment]
+1 on this.

**Comment by RemiAWE** [comment]
@gvaartjes exactly

**Comment by nfantone** [comment]
Also, it should be interesting to see the server with its corresponding `package.json` and dependencies explicitly declared, rather than having to copy files around to make it work.

**Comment by nfantone** [comment]
@RemiAWE Here: https://github.com/nfantone/highcharts-export-server

In the meantime, you could:

```sh
npm install nfantone/highcharts-export-server#develop
```

**Comment by nfantone** [comment]
@RemiAWE  I've published this to npm as **highcharts-phantomjs**

https://www.npmjs.com/package/highcharts-phantomjs

Or course, I've referenced you, @gvaartjes, as the author. I've also updated the doc  and setup a semistandard-config eslint.

**Comment by RemiAWE** [comment]
@nfantone Thank you :+1:

**Comment by nfantone** [comment]
@RemiAWE You are quite welcome.

**Comment by gvaartjes** [comment]
Thanks @nfantone . I'll take a look and see what we can do

**Comment by nfantone** [comment]
@gvaartjes I have published [yet another version of this}(https://www.npmjs.com/package/highcharts-phantomjs). This time, I added a cli tool that completely wraps the server and abstracts away PhantomJS (using [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuil)). 

You may borrow inspiration from that, if you like.

**Comment by nfantone** [comment]
`2.1.2` version (released)[https://www.npmjs.com/package/highcharts-phantomjs].

Pulls down all changes from this repo, so it's up to date with the current [highcharts-convert.js](https://github.com/highcharts/highcharts-export-server/blob/master/phantomjs/highcharts-convert.js).

**Comment by gvaartjes** [comment]
Hi Nicolas, 

I tried to get started with it this week.. just didn't make it.

**Comment by gvaartjes** [comment]
@nfantone I updated the phantomjs script today, there were some serious issues.

**Comment by nfantone** [comment]
I'll try to update the highcharts-phantomjs module as soon as I can. Thanks for the heads up.

**Comment by nfantone** [comment]
@gvaartjes [2.2.0 release](https://www.npmjs.com/package/highcharts-phantomjs) updates [`highcharts-convert.js`](https://github.com/highcharts/highcharts-export-server/blob/master/phantomjs/highcharts-convert.js) to latest, including the use of the new `resources.json` file.

**Comment by gvaartjes** [comment]
Sorry for my late reply, @nfantone . Great work!

**Comment by larsac07** [comment]
Closing this issue, as this is now covered in [the node export server](https://github.com/highcharts/node-export-server)
