### ISSUE TITLE
ServerObjectFactory.create is not thread safe

### ISSUE THREAD

**Issue by javakinglzh** [highcharts/highcharts-export-server#41]
I have a question about the thread safe.
After the server start, immediately thread t1 and t2 request come . They invoke  **ServerObjectFactory.create()** the same time. t1 and t2 both invoke **ServerObjectFactory.getAvailablePort(),** and find **7777** port is valid, so t1 and t2 both invoke new **Server(exec, script, host, port, connectTimeout, readTimeout, maxTimeout)** with 7777. however phantomjs can not start 2 instances with port 7777.
Is this acceptable? thanks!!!

**Comment by javakinglzh** [comment]
Sorry, I make a mistake , t1 and t2 should invoke **serverPool.borrowObject()**, and this is thread block,so it's thread safe, however I can not understand why you create pool?If you use pool, one server can not deal many request at the same time.What is the point? One phantonjs server can deal many http request concurrency, hower now it deal one reqesut .

**Comment by larsac07** [comment]
Hi, @javakinglzh.

First of all, let me recommend that you take a look a the new [nodejs-based export server](https://github.com/highcharts/node-export-server), as we consider this software legacy, and are are discontinuing development.

Now, the Java export server was mostly tuned to satisfy an environment where each phantomjs instance handled one http request at a time, therefore we used a pool and a blocking queue, where many requests can be received and wait for an available server to execute the request. I hope this answers your question.

**Comment by javakinglzh** [comment]
Thanks for your explain, but I still can not understand **why each phantomjs instance handled one http request at a time?** 
Someone tell me **one phantomjs instance can handle 10 Concurrency request**,**why not use one phantomjs instance handle 10 http request, why use 10 phantomjs instances handle 10 http** requests? Which method is more efficient?
Thanks a lot.

**Comment by larsac07** [comment]
@javakinglzh I see where your concern is, but this was at the time tweaked for the export server running at [export.highcharts.com](http://export.highcharts.com) (which the node export server is now running on). Remember that the [Web Server Module is still experimental](http://phantomjs.org/api/webserver/), and controlling multiple request at a time in phantom did not work well for us in a production environment. You may experiment in your own environment as you'd like, to see what configuration works best for you.
