### ISSUE TITLE
Exported image different from the original chart due to not applied styles for axis labels

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-export-server#44]
Only some styles showing as working when comparing the original chart with the exported image.

Ellipsis is not visible and first label is too long - different from the original chart.

Demo:
http://jsfiddle.net/oxpu2ezb/1/

Steps:
1. export and compare with the original chart - first labels is different

Looks like the `useHTML` for axis labels is not respected.

**Comment by larsac07** [comment]
@KacperMadej This is an issue with the [highcharts repo](https://github.com/highcharts/highcharts), and not the export server. The SVG which is sent to the export server is already "erroneous" in that the labels are not HTML markup, but SVG:


```
...
<g class="highcharts-axis-labels highcharts-xaxis-labels ">
        <text x="91.051058197684" style="color:#666666;cursor:default;font-size:11px;white-space:nowrap;fill:#666666;" text-anchor="end" transform="translate(0,0) rotate(-45 91.051058197684 336)" y="336" opacity="1">
            <tspan style="max-width: 50px; display: inline-block; text-overflow: ellipsis; overflow: hidden; white-space: nowrap; fill: red;">Big data for yAxislablel</tspan>
            <title>Big data for yAxis lablel</title>
        </text>
        ...
```

Also, FYI: The export server at [export.highcharts.com](http://export.highcharts.com) which Highcharts uses is the [node export server](https://github.com/highcharts/node-export-server), and not this one.
