### ISSUE TITLE
[highcharts-export-convert][spring] an instance of Server is always created by Spring autowiring

### ISSUE THREAD

**Issue by jbmgrtn** [highcharts/highcharts-export-server#45]
spring-convert.xml contains a bean definition for com.highcharts.export.server.Server.
In that case, Spring creates an instance of Server using the first port available.
This server instance is out of the pool thus useless.
Furthermore the pool will fail to create a server instance for the first port since there's already a PhantomJS listening on that port.
This used to be unnoticed until my pull request issue #42.
Simply deleting the bean definition should correct the problem.

**Comment by larsac07** [comment]
Yes, that was originally added in ad57103 to fix #19, but I see now that it complicates server instantiation. #19 is more of an enhancement anyway, so this should be prioritized. Removing it now.
