### ISSUE TITLE
Highcharts export on MAC Sierra not working

### ISSUE THREAD

**Issue by mcevikce** [highcharts/highcharts-export-server#47]
Recently we upgraded our operating system from El Capitan to Sierra result of this, highcharts export stopped working.
Old environment (WORKS):
MAC OS ElCapitan
phantomJS 1.9.7
about Two years old highcharts-export-server

New environment (Does Not Work):
MAC OS Sierra
We upgraded phantomJS to 2.1 
- using the latest highcharts-export-server running on Tomcat 7 jdk 1.7

Server deploys and starts 10 phantomjs processes. When the server logging in debug mode I can see that each process in the pool gets verified and passed.
Problem happens when a SVG request is server throws the following exception:
ERROR] [http-8080-1 10:53:38] (SVGConverter.java:requestServer:151) com.highcharts.export.converter.SVGConverterException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:7782/

This is the parameter string sent to phantomJS process:
{"infile":"{\"colors\":[\"#7cb5ec\",\"#adadad\",\"#de2900\",\"#f7a35c\",\"#8085e9\",\"#f15c80\",\"#e4d354\",\"#8085e8\",\"#8d4653\",\"#91e8e1\"],\"chart\":{\"zoomType\":\"xy\",\"style\":{\"fontFamily\":\"Carlito,Calibri,sans-serif\"}},\"title\":{\"text\":\"Population\",\"align\":\"center\",\"style\":{\"fontWeight\":\"bold\"}},\"exporting\":{\"sourceWidth\":543,\"sourceHeight\":333},\"credits\":{\"enabled\":false},\"xAxis\":{\"categories\":[2010,2011,2012,2013,2014,2015]},\"tooltip\":{\"shared\":true},\"yAxis\":[{\"title\":\"\",\"labels\":{\"format\":\"{value:,.0f}\"},\"min\":0,\"max\":45000}],\"plotOptions\":{\"line\":{\"dataLabels\":{\"format\":\"{value}%\"}}},\"series\":[{\"name\":\"Armstrong School District\",\"type\":\"column\",\"data\":[43301,43145,43031,42840,42644,42187]},{\"name\":\"CAGR\",\"type\":\"line\",\"data\":[\"\",\"\",\"\",\"\",\"\",\"\"],\"visible\":false}]}","constr":"Chart","type":"svg"}

We have been struggling with this problem with few days now. Unable to resolve it.

**Comment by larsac07** [comment]
@mcevikce It looks like this is solely a OSX Sierra problem, as the latest highcharts-export-server running on Tomcat 8.5.4 and Java 1.8 works just fine with this config on OSX El Capitan. Haven't updated to Sierra yet (due to some issues with e.g. MongoDB), so cannot test it.

I strongly suggest you try out the new [Node.js export server](https://github.com/highcharts/node-export-server), as the phantom+Java/php+batik-solutions are considered legacy.

Did you catch any error output from Phantomjs?

**Comment by larsac07** [comment]
Closing this for now, as there was no response from O.P.

**Comment by zahedalimohammed** [comment]
@larsac07 
I would truly appreciate if you could please help me out in resolving this issue. My scenario is also the same. My colleague accidentally changed Phantomjs from 1.9.8 to 2.1.1. It all got messed up. I would truly appreciate if someone could please help me out with this.

**Comment by zahedalimohammed** [comment]
@larsac07 
I have created the issue at : 
https://github.com/highcharts/highcharts-export-server/issues/54

**Comment by mcevikce** [comment]
We took the recommendation from arsac07  and started to use Node.js export server. That seems to be working fine.

**Comment by zahedalimohammed** [comment]
@mcevikce 
Is there anyway I can run this NodeJs Server on my JBoss as war. If yes, I would truly appreciate if you could please help me out with this.

**Comment by mcevikce** [comment]
No you can’t. It is not a Java web app. You need to start it as a process. I recommend you read into it.
