### ISSUE TITLE
mvn install stuck

### ISSUE THREAD

**Issue by shankarramas** [highcharts/highcharts-export-server#48]
mvn install stuck at:
Downloading: http://snapshots.repository.codehaus.org/org/mortbay/jetty/jetty-ut
il/6.1.5/jetty-util-6.1.5.pom

**Comment by larsac07** [comment]
Hello, @shankarramas, and welcome to GitHub.

Could you please describe the issue you are experiencing? It would really help if you could describe the steps you made that resulted in the issue. For example, the version of the software, the server type and operating system would be a great start.

I'd also strongly recommend that you try moving to [the new Node.js-based export server](https://github.com/highcharts/node-export-server), as this Java+PhantomJS export server is now considered deprecated.

**Comment by shankarramas** [comment]
Hi,
Sure and thanks for getting back. I understand but unfortunately we have to stick with the Java + PhantomJS option.

To the issue in hand, I am following this guide: https://www.highcharts.com/docs/export-module/setting-up-the-server and I have completed till step 1.3. I am stuck in the step 1.4, when I run 'mvn install' the process gets stuck at downloading 'http://snapshots.repository.codehaus.org/org/mortbay/jetty/jetty-ut
il/6.1.5/jetty-util-6.1.5.pom'. Incidentally I am unable to access this url directly from my browser too.

**Comment by larsac07** [comment]
Ok, I need the following information:
- Operating system
- Maven version
- Java version
- PhantomJS version
- highcharts-export-server version (e.g. "newly downloaded from GitHub" or "april 2015")

**Comment by shankarramas** [comment]
OS: Windows 7 Professional, 64-bit
Maven version: Apache Maven 2.2.1 (r801777; 2009-08-07 00:46:01+0530)
Java version: JDK 1.6.0_24
PhantomJS version: 2.0.0
highcharts-export-server version: newly downloaded from GitHub last week

**Comment by larsac07** [comment]
OK, try to upgrade your Maven version to Maven 3, as specified in [1.1 Prerequisites for Installation](https://www.highcharts.com/docs/export-module/setting-up-the-server section)

**Comment by shankarramas** [comment]
Okay, let me try doing that and get back. Thanks!

**Comment by shankarramas** [comment]
I have few more issues now actually. I am stuck with JDK 6. Is there any legacy/archive version of Highcharts Export that runs on JDK 6 and mvn 2?
Even if I did get mvn 3 to build me the jars I **have** to use it against JDK6 but the source code is using lot for newer Java language features that doesn't sit well with the JDK 6 compiler.

**Comment by larsac07** [comment]
I'm sorry, but there is no official legacy version of the highcharts export server which supports JDK 6 and maven 2.

**Comment by shankarramas** [comment]
Yeah... Thank your for your responses though!

**Comment by shankarramas** [comment]
Just to update here so that if some one finds this it may help, when Maven 2 is used it does get stuck when building but as suggested when using Maven 3 I am able to build the war.
