### ISSUE TITLE
Custom marker on locally installed export server

### ISSUE THREAD

**Issue by willifordj** [highcharts/highcharts-export-server#49]
Charts built with a custom marker symbol will display correctly on a web page and rendered to a png using the export function from the context menu. The custom marker will not render using a locally installed version of highcharts-export-server, but the standard marker is OK.

highcharts-export-server is installed on a Windows 7 PC.  Highcharts, NodeJS and highcharts-export-server are the latest versions.

The export server was installed using instructions at:
https://www.highcharts.com/docs/export-module/render-charts-serverside

An example jsfiddle is here:
http://jsfiddle.net/adkkqkwm/16/

**Comment by larsac07** [comment]
Hi, @willifordj. This is the legacy highcharts export server repository. For the new NodeJS based export server, visit https://github.com/highcharts/node-export-server

**Comment by willifordj** [comment]
Thank you for the response.  The export server was installed using these instructions and did not render the custom markers.

•	First, make sure you have node.js installed. Go to nodejs.org and download/install node for your platform.
•	After node.js is installed, install the export server by opening a terminal and typing:
•	npm install highcharts-export-server –g


There were no errors or warnings in the level 4 log. 
Is there a way to identify the installed version of highcharts-export-server?

**Comment by larsac07** [comment]
@willifordj What you are referring to is the node-export-server. The legacy export server (this repository) has nothing to do with NodeJS
