### ISSUE TITLE
marker:{symbol:'url(...)'} does not work in SVG output by PhantomJS

### ISSUE THREAD

**Issue by dadza** [highcharts/highcharts-export-server#7]
The problem can be reproduced with http://export.highcharts.com/demo with the following config object:

```js
{
        series: [{
            data: [216.4, 194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5],
            marker: {
                symbol: 'url(https://www.highcharts.com/samples/graphics/sun.png)'
            }
        }]
}
```

Downloading a SVG file results in a document that contains the marker image elements, but with width="0" height="0" (which makes the markers not visible).

Running the convert script locally in PhantomJS results in the same output.

PNG and PDF outputs are fine.

**Comment by TorsteinHonsi** [comment]
The differences is that the SVG is returned directly from the page, while PNG and others are waiting for images to download. 

I have prepared a fix for this issue by [modifying the load event](https://github.com/highcharts/highcharts/commit/8c745002445106a22ebc56bb9c332ee5222b03de) in Highcharts. It now waits for images before it fires async.

Next step is to wait for the Highcharts upgrade, then change the export script to use the `load` event instead.

**Comment by dadza** [comment]
Torstein, have you considered also delaying the invocation of the chart callback (passed as constructor argument) until the images are loaded?

The current documentation reads "callback: A function to execute when the chart object is finished loading and rendering ... Defining a chart.event.load handler is equivalent."

**Comment by TorsteinHonsi** [comment]
> Torstein, have you considered also delaying the invocation of the chart callback (passed as constructor argument) until the images are loaded?

That makes sense, I'll do that modification. The whole point of the callback is to wait for async processes.

**Comment by TorsteinHonsi** [comment]
Implemented: https://github.com/highcharts/highcharts/commit/f2300c9ed8075ff66e60e6c8d754313669bed9ee
