### ISSUE TITLE
Apache error in demo.jsp page

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts-export-server#8]
This is problem with this line: https://github.com/highcharts/highcharts-export-server/blob/master/java/highcharts-export/highcharts-export-web/src/main/webapp/WEB-INF/pages/demo.jsp#L12

We have 2x `//` in the path. It will break the page in the Apache, but works fine with Tomcat.

**Comment by gvaartjes** [comment]
Fixed by 9f44c62523402481291cc973e2eb1afe90222a7c
