### ISSUE TITLE
Webfonts are not exported.

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts-export-server#9]
Use of webfonts defined in the chart configuration are not used in the exported image. This is of course because PhantomJS doesn't recognize the font-family.

Are we going to support this? Perhaps as a defined style/theme post parameter?

**Comment by TorsteinHonsi** [comment]
If we think broader, we may be able to support CSS files in general, as a post parameter. But we still need some async trickere to wait for the CSS file to load the actual font files.

**Comment by jerrydy** [comment]
Is there a workaround for us to use our own fonts via css?

**Comment by TorsteinHonsi** [comment]
> If we think broader, we may be able to support CSS files in general, as a post parameter.

Even broader than that, it could be a general `resources` post parameter that can take CSS or JS files and insert them into the page template. That would resolve web fonts.

> Is there a workaround for us to use our own fonts via css?

Yes, check out [client side export](http://www.highcharts.com/docs/export-module/client-side-export).

**Comment by larsac07** [comment]
Closing this, as further enhancements will not be implemented on this repo (new export server at https://github.com/highcharts/node-export-server)
